export const svgIcon  = {
	"search": "PacvueIconSearch",
	"remove": "PacvueIconRemove",
	"add": "PacvueIconAdd",
	"tips-exclamation": "PacvueIconTipsExclamation",
	"widget-setting": "PacvueIconWidgetSetting",
	"36) icon/star": "PacvueIconStarfill",
	"add to subtag": "PacvueIconAddToSubtag",
	"save": "PacvueIconSave",
	"eye": "PacvueIconEye",
	"download": "PacvueIconDownload",
	"upload": "PacvueIconUpload",
	"active explorer": "PacvueIconActiveExplorer",
	"all explorer": "PacvueIconAllExplorer",
	"auto": "",
	"manual": "PacvueIconManual",
	"all-auto&manual": "PacvueIconAllAutoManual",
	"day parting": "PacvueIconDayParting",
	"replay": "PacvueIconReplay",
	"Filter scenes": "PacvueIconFilterScenes",
	"Filter combinations": "PacvueIconFilterCombinations",
	"edit": "PacvueIconEdit",
	"email": "PacvueIconEmail",
	"arrow-drop-down": "PacvueIconArrowDropDown",
	"arrow-drop-up": "PacvueIconArrowDropUp",
	"arrow-left": "PacvueIconArrowLeft",
	"arrow-right": "PacvueIconArrowRight",
	"import-export": "PacvueIconImportExport",
	"Budget schedule": "PacvueIconBudgetSchedule",
	"more": "PacvueIconMore",
	"Active default tag": "PacvueIconActiveDefaultTag",
	"Document": "PacvueIconDocument",
	"refresh": "PacvueIconRefresh",
	"markread": "PacvueIconMarkread",
	"Notification": "PacvueIconNotification",
	"unbind": "PacvueIconUnbind",
	"Edit Profile": "PacvueIconEditProfile",
	"Ignore": "PacvueIconIgnore",
	"explor": "PacvueIconExplor",
	"change live": "PacvueIconChangeLive",
	"switch": "PacvueIconSwitch",
	"close": "PacvueIconClose",
	"view log": "PacvueIconViewLog",
	"delete": "PacvueIconDelete",
	"Component 2": "PacvueIconComponent2",
	"Negative targeting": "PacvueIconNegativeTargeting",
	"from negative keyword": "PacvueIconFromNegativeKeyword",
	"detail": "PacvueIconDetail",
	"Manage": "PacvueIconManage",
	"Accessible account": "PacvueIconAccessibleAccount",
	"Component 1": "PacvueIconComponent1",
	"Log": "PacvueIconLog",
	"menu-fold": "PacvueIconMenuFold",
	"menu-unfold": "PacvueIconMenuUnfold",
	"add to campaign": "PacvueIconAddToCampaign",
	"copy": "PacvueIconCopy",
	"edit-details": "PacvueIconEditdetails",
	"view sov": "PacvueIconViewSov",
	"keyword detail": "PacvueIconKeywordDetail",
	"add to keyword tag": "PacvueIconAddToKeywordTag",
	"tag keywords": "PacvueIconTagKeywords",
	"audit again": "PacvueIconAuditAgain",
	"detail-chart": "PacvueIconDetailChart",
	"reset": "PacvueIconReset",
	"list": "PacvueIconList",
	"User Management": "PacvueIconUserManagement",
	"keyword expansion": "PacvueIconKeywordExpansion",
	"asin expansion": "PacvueIconAsinExpansion",
	"exclude": "PacvueIconExclude",
	"Product Insight": "PacvueIconProductInsight",
	"Add creative": "PacvueIconAddCreative",
	"Balance": "PacvueIconBalance",
	"exclamation": "PacvueIconExclamation",
	"Analysis": "PacvueIconAnalysis",
	"Performance chart": "PacvueIconPerformanceChart",
	"landscape": "PacvueIconLandscape",
	"last period data": "PacvueIconLastPeriodData",
	" drag": "PacvueIconDrag",
	"visibility-off": "PacvueIconVisibilityOff",
	"Monthly Rollover": "PacvueIconMonthlyRollover",
	"Switch to plan": "PacvueIconSwitchToPlan",
	"Switch to metrics": "PacvueIconSwitchToMetrics",
	"rule": "PacvueIconRule",
	"AI": "PacvueIconAi",
	"calendar setting": "PacvueIconCalendarSetting",
	"Bulk Creation Price Tracker": "PacvueIconBulkCreationPriceTracker",
	"convert to": "PacvueIconConvertTo",
	"select Brand": "PacvueIconSelectBrand",
	"show full number": "PacvueIconShowFullNumber",
	"bulk operation": "PacvueIconBulkOperation",
	"run again": "PacvueIconRunAgain",
	"overview": "PacvueIconOverview",
	"audit history": "PacvueIconAuditHistory",
	"Username": "PacvueIconUsername",
	"User Roles": "PacvueIconUserRoles",
	"Date Format": "PacvueIconDateFormat",
	"Time Zone": "PacvueIconTimeZone",
	"Wasted ad spend Reduce bids": "PacvueIconWastedAdSpendReduceBids",
	"Reduce bids": "PacvueIconReduceBids",
	"Increase bids": "PacvueIconIncreaseBids",
	"Increase reach": "PacvueIconIncreaseReach",
	"跳转": "",
	"back": "",
	"manage tag": "PacvueIconManageTag",
	"Platform": "PacvueIconPlatform",
	"fangda": "",
	"Apply": "PacvueIconApply",
	"Heat Map": "PacvueIconHeatMap",
	"recommdation": "PacvueIconRecommdation",
	"tag": "PacvueIconTag",
	"notes": "PacvueIconNotes",
	"Chart Control": "PacvueIconChartControl",
	"Add ASIN as PAT to": "PacvueIconAddAsinAsPatTo",
	"Vector": "PacvueIconVector",
	"redo": "PacvueIconRedo",
	"Custom Columns": "PacvueIconCustomColumns",
	"Add to asin tag": "PacvueIconAddToAsinTag",
	"add keyword": "PacvueIconAddKeyword",
	"autorenew": "PacvueIconAutorenew",
	"Designate Brand Tag": "PacvueIconDesignateBrandTag",
	"chevrons-right": "PacvueIconChevronsRight",
	"export": "PacvueIconExport",
	"send again": "PacvueIconSendAgain",
	"refresh data and send again": "PacvueIconRefreshDataAndSendAgain",
	"show abbreviate number": "PacvueIconShowAbbreviateNumber",
	"view history": "PacvueIconViewHistory",
	"Set bid": "PacvueIconSetBid",
	"real time data": "PacvueIconRealTimeData",
	"Column Chart": "PacvueIconColumnChart",
	"Line Chart": "PacvueIconLineChart",
	"Vendor": "PacvueIconVendor",
	"Seller": "PacvueIconSeller",
	"Retail Dashboard": "PacvueIconRetailerDashboard",
	"Share Center": "PacvueIconShareCenter",
	"Keyword Opporyunity": "PacvueIconKeywordOpporyunity",
	"Not Override ASIN": "PacvueIconOverrideAsin",
	"Override ASIN": "PacvueIconNotOverrideAsin",
	"Leader": "PacvueIconLeader",
	"Super admin": "PacvueIconSuperAdmin",
	"  admin": "PacvueIconAdminGrey",
	"Assign to Campaigns": "PacvueIconAssignToCampaigns",
	"Merge to Deal Term": "PacvueIconMergeToDealTerm",
	"Merge Other Deal Terms": "PacvueIconMergeOtherDealTerms",
	"close-circle-fill": "PacvueIconCloseCircleFill",
	"wiget-drag": "PacvueIconWigetDrag",
	"ASIN warning Orange": "PacvueIconAsinWarningOrange",
	"ASIN warning red": "PacvueIconAsinWarningred",
	"star-fill": "PacvueIconStarfill",
	"star gray": "PacvueIconStar",
	"weixuan": "PacvueIconWeixuan",
	"Add to Targeting": "PacvueIconAddtotargeting",
	"filter-check": "PacvueIconFilterCheck",
	"loading": "PacvueIconLoading",
	"crown": "PacvueIconCrown",
	"云下载 1": "PacvueIconCommerceDownloadCenter",
	"binding": "PacvueIconBinding",
	"rank": "PacvueIconRank",
	"zhiding": "PacvueIconZhiding",
	"pat detail": "PacvueIconPatDetail",
	"Arrow left": "PacvueIconLeftArrow",
	"Arrow Right": "PacvueIconRightArrow",
	"展开": "",
	"mobile": "PacvueIconMobile",
	"pc": "PacvueIconPc",
	"import": "PacvueIconImportExport",
	"Audience Expansion": "PacvueIconAudienceExpansion",
	"Row height": "PacvueIconRowHeight",
	"collect and topping": "",
	"refresh bid": "",
	"sparkles": "PacvueIconSparkles",
	"Authorize": "PacvueIconAuthorize",
	"separate 1": "",
	"Pause": "",
	"Shopping, buybox": "PacvueIconShoppingCart",
	"Ticket 、coupon": "PacvueIconDiscountCoupon",
	"Skip": "PacvueIconSkip1",
	"top bar-arrow-down": "PacvueIconTopBarArrowDown",
	"IconCursorMouse/size4":""
}